### PR TITLE
Upgrade to RA v4 // MUI v5, improved styling, proper SemVer display, ...

### PR DESCRIPTION
**Pull request by shaunco**
feat: react-admin-v4
feat: mui v5
fix: new tree menu
feat: UI / style enhancements
feat: SemVerChip and SemVerTextField for #3
fix: TrimField for all long fields in table views
fix: true/1 vs false/0 handling on connection states for #2

### CODE REVIEW

**Comment by dcaputo-harmoni** [comment]
Wow - thank you for the PR! I will review all of this ASAP, these all sounds like great fixes / enhancements.

**Comment by dcaputo-harmoni** [comment]
@shaunco this is OUTSTANDING work - thank you for contributing it.  When I created this repo, I put it out to the community for this exact reason - with the hope that others would be just as passionate about this as I am, and help contribute to make it better.  This was exactly what I was hoping for.

Overall, I love all of these changes.  There were a few snags that I hit in testing, wondering if you could help with them:

- The hot module replacement / auto reloading wasn't working in my local dev environment, is there something I need to do to enable this?  I'm running with NODE_ENV=development
- The device connect (remote ssh) functionality doesn't seem to work from the main dashboard (but works fine in other places).  I get the error `Cannot read properties of undefined (reading 'uuid')` from the DeviceConnect endpoint, looks like it's not getting the device context properly?
- The delete button on the releases page is disabled for releases where it should be enabled (i.e. releases with no devices running them)
- In `components/release.js`, looks like line 44 needs to be changed from `export const ReleaseList = () => {` to `export const ReleaseList = (props) => {`

Otherwise I think this is good to go, clearly you guys have put a lot of time into testing this, it works great.

**Comment by shaunco** [comment]
@julianocomg did all the heavy lifting here! We have more underway that we'll contribute back soon.

For your questions:

- If you have a `.env` file in the root (next to `.gitignore` with `NODE_ENV=development`, you should be good to go through either running `npm start devserver` or by hitting F5 in VSCode. I'm not sure why else it might not work, but perhaps @julianocomg has some ideas
- We were overly light on testing for remote SSH, as open-balena-remote doesn't work in our setup _(we can't use ports 10000+ and need everything to go over 80/443. We're working to redo the remote stuff as websockets, but it will be a few weeks)_. The issue here is likely that ra-4 moves to react-router-v6, which drops all `props` support in favor of `useParams()`, `useQuery()`, and other hooks (see the [Upgrade Guide](https://marmelab.com/react-admin/Upgrade.html#react-router-v6)). Chances are we missed one here, and thus uuid is undefined because we are missing a `const { uuid } = useParams()`.
- Will take a look
- Will take a look

**Comment by dcaputo-harmoni** [comment]
@shaunco all sounds great - thanks for the color.  Those changes to `open-balena-remote` will be a major improvement over the rotating port system used now, looking forward to that.  If you are running `open-balena` in a production environment, I'd encourage you to check out the [helm charts](https://github.com/dcaputo-harmoni/open-balena-helm) that we created, they include a lot of other production-ready components that have been developed such as loki logging / grafana reporting, build servers, delta servers, and more.

**Comment by dcaputo-harmoni** [comment]
@suaunco in the meanwhile I'll merge this in so I can help with a few other things, and update docs etc.

**Comment by dcaputo-harmoni** [comment]
@shaunco @julianocomg quick update for you guys here, I've managed to work through most of the issues with the new code, and the fixes are included in [this branch](https://github.com/dcaputo-harmoni/open-balena-ui/tree/dcaputo/tweaks-to-major-update).  As of now, all remote device connectivity is working (including ssh, vnc and http) and the issues noted above (with the exception of the release deletion button) are fixed, among other small tweaks.  I should be able to get to the release deletion button soon as well.  We're also now using the new interface in our environment, so I'll continue to work in additional tweaks / fixes as they inevitably come in.

**Pull request merged**
